# Generated by Django 5.1.6 on 2025-02-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_departmentpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentPage',
        ),
    ]
