# Generated by Django 5.1.6 on 2025-02-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_announcementpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementpage',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='departmentpage',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
