# Generated by Django 5.1.6 on 2025-02-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_announcementitem'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Description of this announcement section')),
            ],
            options={
                'verbose_name': 'Announcement Section',
                'verbose_name_plural': 'Announcement Sections',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubAnnouncementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('announcement_content', models.TextField(help_text='Content of the announcement')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='announcementpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='departmentannouncement',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='departmentpage',
            options={},
        ),
        migrations.DeleteModel(
            name='AnnouncementItem',
        ),
        migrations.DeleteModel(
            name='AnnouncementPage',
        ),
        migrations.DeleteModel(
            name='DepartmentAnnouncement',
        ),
    ]
